version: '3'
services:
  node1:
    build: .
    image: bitcoind:0.17.0
    ports:
      - "18400:18443"
      - "18500:18444"
    expose: 
      - "18444"
    command: [ "-regtest", "-addnode=node2:18444", "-addnode=node3:18444"]
  node2:
    image: bitcoind:0.17.0
    ports:
      - "18401:18443"
      - "18501:18444"
    expose: 
      - "18444"
    command: [ "-regtest", "-addnode=node1:18444", "-addnode=node3:18444"]
  node3:
    image: bitcoind:0.17.0
    ports:
      - "18402:18443"
      - "18502:18444"
    expose: 
      - "18444"
    command: [ "-regtest", "-addnode=node1:18444", "-addnode=node2:18444"]
