version: '3.2'
services:
  master:
    build: .
    image: bitcoind:0.17.1
    volumes:
      - type: bind
        source: /mnt/bitcoin/cluster/1
        target: /bitcoind-data
    healthcheck:
      test: ["CMD", "bitcoin-cli", "getblockchaininfo"]
      interval: 30s
      timeout: 20s
      retries: 5
  node2:
    image: bitcoind:0.17.1
    volumes:
      - type: bind
        source: /mnt/bitcoin/cluster/2
        target: /bitcoind-data
  node3:
    image: bitcoind:0.17.1
    volumes:
      - type: bind
        source: /mnt/bitcoin/cluster/3
        target: /bitcoind-data
  stunnel:
    image: dweomer/stunnel
    environment:
      - STUNNEL_SERVICE=bitcoind-tls
    depends_on:
      - master
